[theme]
primaryColor = "#fcfcfc"        # White, used for accents and interactive widgets
backgroundColor = "#E0E0E0"     # Light gray, used in the main content area of the app
secondaryBackgroundColor = "#84BABF"  # Light teal, for secondary elements and added contrast
textColor = "#333333"           # Dark gray for text, ensuring good readability
font = "sans serif"
base = "light"                  # A light base to keep the theme bright and airy
